# Local development
version: '3.8'
services:

  postgres:
    image: 'postgres:16-bookworm'
    networks:
      - overlay
    ports:
      - "5432:5432"
      # We only expose the port here for local dev purposes
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: regatta

  postgressetup:
    build:
      context: ./postgres_init
      dockerfile: Dockerfile
    depends_on:
      - postgres
    networks:
      - overlay
    restart: "no"
    volumes:
      - ./postgres_init/scripts:/postgres_init
    environment:
      PGUSER: admin
      PGPASSWORD: mysecretpassword
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: regatta

    entrypoint: [ "/postgres_init/postgres_init.sh" ]


networks:
  overlay:
