const val kotlinVersion = "2.3.0"
const val ktorVersion = "3.4.0"
const val logbackVersion = "1.4.11"
const val composeVersion = "1.10.0"
const val serializationVersion = "1.10.0"
const val exposedVersion = "1.0.0"
const val coroutinesVersion = "1.10.2"
